excel_file: "data/Book1.xlsx"
excel_sheet_name: "BC - Business Rule"
processed_rules_file: "data/processed_rules.json"
constrains_processed_rules_file: "data/constrains_processed_rules.json"
generated_test_cases_file: "data/generated_test_cases.json"
test_case_keys_file: "data/test_case_with_keys.json"
# generated_test_cases_file: "data/anth1.json"
gemini_model: "gemini-1.5-flash"
gemini_api_key: "AIzaSyCfWqJvycPgVnUrl_OjIN5nzSQxm_iBlw4"
openai_api_version: "2024-06-01"
azure_openai_endpoint: "https://prod-1.services.unitedaistudio.uhg.com/aoai-shared-openai-prod-1"
deployment_name: "gpt-4o_2024-05-13"
model_name: "gpt-4o"
project_id: "0bef8880-4e98-413c-bc0b-41c280fd1b2a"
